# Define the services (containers) for our application
services:
  # Our database service
  postgres:
    image: postgres:16-alpine  # Use the official PostgreSQL 16 image, 'alpine' version (lighter)
    container_name: myprofile-postgres # Name the container for easy identification
    restart: always # Ensure the container restarts automatically if it stops
    environment:
      # Define environment variables to configure the database
      POSTGRES_USER: myprofileuser
      POSTGRES_PASSWORD: myprofilepassword
      POSTGRES_DB: myprofile_dev
    ports:
      # Map port 5432 of the container to port 5432 of your machine
      # Format: "HOST:CONTAINER"
      - '5432:5432'
    volumes:
      # Create a volume to persist the database data
      # This ensures data is not lost when restarting the container
      - postgres_data:/var/lib/postgresql/data

# Define the volumes that Docker will manage
volumes:
  postgres_data:
    driver: local